//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prepull {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrepullStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrepullStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prepull.PrepullStrings", typeof(PrepullStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The random config bool is {0}.
        /// </summary>
        internal static string ConfigBool {
            get {
                return ResourceManager.GetString("ConfigBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default to main tank.
        /// </summary>
        internal static string DefaultMainTank {
            get {
                return ResourceManager.GetString("DefaultMainTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakpoint to repair gear (%).
        /// </summary>
        internal static string GearRepairBreakpoint {
            get {
                return ResourceManager.GetString("GearRepairBreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a goat:.
        /// </summary>
        internal static string Goat {
            get {
                return ResourceManager.GetString("Goat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens up window to set up default behaviors.
        /// </summary>
        internal static string HelpMessageConfigWindow {
            get {
                return ResourceManager.GetString("HelpMessageConfigWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens up window to set up prepull parameters.
        /// </summary>
        internal static string HelpMessageMainWindow {
            get {
                return ResourceManager.GetString("HelpMessageMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not found.
        /// </summary>
        internal static string ImageNotFound {
            get {
                return ResourceManager.GetString("ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepull##With a hidden ID.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be in an instance!.
        /// </summary>
        internal static string NotInInstance {
            get {
                return ResourceManager.GetString("NotInInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh food!.
        /// </summary>
        internal static string RefreshFood {
            get {
                return ResourceManager.GetString("RefreshFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh food reminder (mins).
        /// </summary>
        internal static string RefreshFoodTimer {
            get {
                return ResourceManager.GetString("RefreshFoodTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair gear!.
        /// </summary>
        internal static string RepairGear {
            get {
                return ResourceManager.GetString("RepairGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show settings.
        /// </summary>
        internal static string ShowSettings {
            get {
                return ResourceManager.GetString("ShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summon pet.
        /// </summary>
        internal static string SummonPet {
            get {
                return ResourceManager.GetString("SummonPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main tank.
        /// </summary>
        internal static string ToggleMainTank {
            get {
                return ResourceManager.GetString("ToggleMainTank", resourceCulture);
            }
        }
    }
}
